# - Create a new deployment in a file called quote.yaml
# - Name the deployment and name the app lavel quote-service
# - Use the development namespace
# - Name the container quote-container
# - Run 2 replicas
# - Use the image datawire/quote:0.5.0
# - Set the container to accept traffic at port 8080
# - Create the pods using 'kubectl apply -f quote.yaml'
# - (Stretch) Use BusyBox to test that the application can accept traffic from inside the cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
  namespace: development
  labels:
    app: quote-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
        - name: quote-container
          image: datawire/quote:0.5.0
          ports:
            - containerPort: 8080
